title: Fasmine lee
email: fasminelee@gmail.com

# Site settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "http:fasminelee.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: fasminelee
github_username:  fasminelee

# Build settings
markdown: kramdown
# theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
